name: minds_mobile_sdk_flutter_demo
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  brasil_fields: ^1.11.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  permission_handler: ^10.2.0
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
